### ISSUE TITLE
Using sd card with bigger storage

### ISSUE THREAD

**Issue by smdgenesis** [cfw-guide/dsi.cfw.guide#15]
I did follow the guide to install Unlaunch then went to install Hiyacfw, i used the Hiya-helper correctly (it says "Done, eject your sd card" at the end of the process) but when i turn my dsi on and click on options (HiyaCFW activation part) there's no HiyaCFW in the menu, i reformatted my sd card multiple times without any luck, please help.
P.S: i'm using 8gb sd card.

**Comment by NightYoshi370** [comment]
Not an issue with the guide. Please ask on the DS(i) Mode Hacking or NDS(i)BREW Scene Discord Server
