### ISSUE TITLE
GUI `HiyaCFW-Helper` fork is deprecated, yet is recommended.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [cfw-guide/dsi.cfw.guide#160]
https://github.com/cfw-guide/dsi.cfw.guide/blob/5cd9e32d3ae7f6d8701976ac19f6801d74d9142d/docs/dumping-nand.md?plain=1#L44:~:text=can%20use%20the-,%5BhiyaCFW%20Helper%5D(https://github.com/mondul/HiyaCFW%2DHelper/releases),-to%20create%20a recommends https://github.com/mondul/HiyaCFW-Helper/releases/tag/v3.6.10:

> The SHA1 hash of the nand.bin will not match the hash stored in nand.bin.sha1. This is because dumpTool adds additional data known as a no$gba footer to the nand.bin file after the SHA1 hash is calculated. You can use the [hiyaCFW Helper](https://github.com/mondul/HiyaCFW-Helper/releases) to create a copy without the footer.

However, https://github.com/mondul/HiyaCFW-Helper/ is archived.

**Comment by RocketRobz** [comment]
Why is this an issue? Do you know of a similar tool?

**Comment by rokejulianlockhart** [comment]
Nope, but we can't rely on unmaintained tools, surely?

**Comment by NightScript370** [comment]
One who wants to maintain it can choose to fork the repo. The main repo being archived is no issue, as long as we're within the license that we can make forks (which the GitHub-granted license very much lets us do that)

**Comment by Peter0x44** [comment]
If it really matters that you're using a "deprecated" tool, you can just manually remove the last 64 bytes of the nand backup with a hex editor manually, then hash the resulting file. It's really a non-issue anyway

**Comment by RokeJulianLockhart** [comment]
> https://github.com/cfw-guide/dsi.cfw.guide/issues/160#issuecomment-1756171814

@Peter0x44, thanks. I wasn't aware it was that trivial. Perhaps re-close this issue as unplanned.
