### ISSUE TITLE
Provide progress indicator on splash screen?

### ISSUE THREAD

**Issue by RokeJulianLockhart** [cfw-guide/dsi.cfw.guide#161]
The menu appears to take a while to load for me, so I'd like to be able to see its progress.

**Comment by lifehackerhansol** [comment]
This isn't related to the guide.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/cfw-guide/dsi.cfw.guide/issues/161#issuecomment-2351704158

@lifehackerhansol, apologies. It's been a while since I read this guide - do you reckon you know what tool I was referring to...?
