### ISSUE TITLE
Required to change file name to copy _nds to root of sd card

### ISSUE THREAD

**Issue by liamwiens** [cfw-guide/dsi.cfw.guide#165]
<img width="338" alt="Screenshot 2023-12-03 135435" src="https://github.com/cfw-guide/dsi.cfw.guide/assets/152815562/4ac68c94-f049-459a-8c7f-5c7e101e6b47">
How would one get passed this error without changing the file name?

**Comment by NightScript370** [comment]
If "sd:/_nds/GBARunner2_arm7dldi_dsi.nds" is too long, then there must be something with your SD.
Could we see what you're calling "root"?

**Comment by SleepyLark** [comment]
Make sure you extracted all the files first from the .7z before you copy them over if you haven't already. That's usually what I've seen cause this kind of problem before

**Comment by liamwiens** [comment]
Can't believe I had noticed. Thanks for the help.
