### ISSUE TITLE
SD Card Setup on Windows with diskpart

### ISSUE THREAD

**Issue by malvarenga123** [cfw-guide/dsi.cfw.guide#169]
I think using diskpart on Windows would be the simplest way to avoid any issues regarding the SD card.

```
diskpart
list disk          (lists available disks, write down the correct number for your USB drive)
select disk N      (replace N with the USB drive number you wrote down)
clean
create partition primary
select partition 1
active
format unit=32k fs=fat32 quick
assign
exit
```
If any of those steps fail, the SD card cannot be used.

**Comment by NightScript370** [comment]
> the simplest way to avoid any issues regarding the SD card.

What issues exist that diskpart takes care of that SD Card Formatter can't (beyond needing to be downloaded + installed)?

**Comment by malvarenga123** [comment]
> What issues exist that diskpart takes care of that SD Card Formatter can't (beyond needing to be downloaded + installed)?

Someone was having issues with a SD card on GBATemp and it was suggested that there could be an extra partition on the card. diskpart clean will make sure that isn't the issue.

**Comment by Deletecat** [comment]
SD Card Formatter will wipe all of the partitions on the SD card so an extra partition shouldn't be an issue

**Comment by malvarenga123** [comment]
I wasn't aware of that.
