### ISSUE TITLE
Unlaunch doesn't autolaunch SuperCardDSTwo plus

### ISSUE THREAD

**Issue by floppydisk-96** [cfw-guide/dsi.cfw.guide#17]
Tried to autoboot/launch supercard ds two plus from unlaunch but the cart appears with this name: "ooooooooooooooooo" and when selected to autoboot, it won't boot, just a blank screen.

**Comment by NightYoshi370** [comment]
Not an issue with the guide. Please mention this to nocash on the NESDEV forums
