### ISSUE TITLE
Fat Mismatch Fix

### ISSUE THREAD

**Issue by coolhaus** [cfw-guide/dsi.cfw.guide#59]
I just wanted to add my own experiences to the guide if anyone else has the Fat Mismatch error from using TWLnf you can fix it easily by deleting all the DSiware on your device and installing the 3ds transfer tool from the DSi e-Shop. This is ultimately what fixed the fat mismatch error for me when I tried to use unLaunch. Hope this helps!

**Comment by NightYoshi370** [comment]
Hah, great find. I'll definitely add this to my guide rewrite. Thank you so much
