### ISSUE TITLE
Extremely Small Issue

### ISSUE THREAD

**Issue by dwain12435** [cfw-guide/dsi.cfw.guide#60]
NEVER MIND!!!

**Comment by urmum-69** [comment]
Yes, the hiyacfw helper itself requires 7-zip installed now.
We don't say you must download completely unneeded programs.

**Comment by dwain12435** [comment]
Ummm... How did you even know what I wrote? I deleted my issue like a
minute after opening it because I realized this.

**Comment by YourKalamity** [comment]
everything in the issues tab is sent to a discord channel

**Comment by Epicpkmn11** [comment]
Also on GitHub you can view the edit history, click the `edited` on the bar above the message

**Comment by dwain12435** [comment]
Yeah, I deleted the first version using that menu.
