### ISSUE TITLE
Unlaunch Website is down.

### ISSUE THREAD

**Issue by 80KiloMett** [cfw-guide/dsi.cfw.guide#65]
Right now the [Website of Unlaunch developer nocash](https://problemkaputt.de) returns 403. I noticed this two days ago when I set up my DSi for Homebrew.

I was able to get my hands on Unlaunch through the [Wayback Machine](https://archive.org/web/). This also revealealed that the Website was still accessible last month.

If this is a permanent issue, it might be good to change the link in the guide to a Wayback-Machine-Link

**Comment by YourKalamity** [comment]
Robz fixed this with the commit 749adb30361c86bb2dc904a5ece8d4bcfc993587 - though I don't think it's a permanent issue.

**Comment by 80KiloMett** [comment]
Sorry, didn't check again before posting the issue. 😅
